name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild -project GitHub.xcodeproj -scheme iOS -sdk iphonesimulator build
    - name: Run tests
      run: xcodebuild -project GitHub.xcodeproj -scheme iOS -sdk iphonesimulator test
    - name: Run a one-line script
      run: echo Hello, world!
